#pragma once

// CB Instructions
int rlc_b(void);
int rlc_c(void);
int rlc_d(void);
int rlc_e(void);
int rlc_h(void);
int rlc_l(void);
int rlc_hl(void);
int rlc_a(void);
int rrc_b(void);
int rrc_c(void);
int rrc_d(void);
int rrc_e(void);
int rrc_h(void);
int rrc_l(void);
int rrc_hl(void);
int rrc_a(void);
// 0x1-
int rl_b(void);
int rl_c(void);
int rl_d(void);
int rl_e(void);
int rl_h(void);
int rl_l(void);
int rl_hl(void);
int rl_a(void);
int rr_b(void);
int rr_c(void);
int rr_d(void);
int rr_e(void);
int rr_h(void);
int rr_l(void);
int rr_hl(void);
int rr_a(void);
// 0x2-

// 0x3-
int swap_b(void);
int swap_c(void);
int swap_d(void);
int swap_e(void);
int swap_h(void);
int swap_l(void);
int swap_hl(void);
int swap_a(void);